#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""问答复制与导出操作（供回答区右键菜单调用）。"""

import logging
import os
import re
from datetime import datetime

from PyQt5.QtWidgets import QApplication, QFileDialog, QMessageBox, QToolTip
from PyQt5.QtGui import QCursor, QTextDocument
from PyQt5.QtPrintSupport import QPrinter

from calibre_plugins.ask_ai_plugin.config import get_prefs

logger = logging.getLogger(__name__)


def show_action_feedback(widget, message):
    QToolTip.showText(QCursor.pos(), message, widget)


def get_response_text(panel):
    """获取面板回答纯文本。"""
    if panel.response_handler and getattr(panel.response_handler, '_response_text', ''):
        return panel.response_handler._response_text
    if panel.response_handler and getattr(panel.response_handler, '_stream_response', ''):
        return panel.response_handler._stream_response
    return panel.response_area.toPlainText()


def get_ai_display_name(ai_name):
    display_names = {
        'openai': 'OpenAI',
        'grok': 'Grok',
        'gemini': 'Gemini',
        'deepseek': 'DeepSeek',
        'anthropic': 'Claude',
        'nvidia': 'Nvidia',
        'openrouter': 'OpenRouter',
        'ollama': 'Ollama',
        'custom': 'Custom',
    }
    return display_names.get(ai_name.lower(), ai_name.capitalize())


def format_qa_content(panel, question, response, include_metadata=True, include_model_info=True):
    """统一格式化问答内容。"""
    i18n = panel.i18n
    dialog = panel.parent_dialog
    separator = "────"
    content_parts = []

    if include_metadata and hasattr(dialog, 'books_metadata') and dialog.books_metadata:
        books_metadata = dialog.books_metadata
        is_multi_book = len(books_metadata) > 1
        content_parts.append(i18n.get('pdf_book_metadata', 'BOOK METADATA'))
        content_parts.append(separator)
        for idx, book_metadata in enumerate(books_metadata, 1):
            if is_multi_book:
                content_parts.append(f"[{i18n.get('book', 'Book')} {idx}]")
            if book_metadata.get('title'):
                content_parts.append(
                    f"{i18n.get('metadata_title', 'Title')}: {book_metadata['title']}"
                )
            if book_metadata.get('authors'):
                authors = ', '.join(book_metadata['authors'])
                content_parts.append(
                    f"{i18n.get('metadata_authors', 'Authors')}: {authors}"
                )
            if book_metadata.get('publisher'):
                content_parts.append(
                    f"{i18n.get('metadata_publisher', 'Publisher')}: {book_metadata['publisher']}"
                )
            if book_metadata.get('pubdate'):
                content_parts.append(
                    f"{i18n.get('metadata_pubdate', 'Publication Date')}: {book_metadata['pubdate']}"
                )
            if book_metadata.get('languages'):
                langs = ', '.join(book_metadata['languages'])
                content_parts.append(
                    f"{i18n.get('metadata_language', 'Languages')}: {langs}"
                )
            if is_multi_book and idx < len(books_metadata):
                content_parts.append("")
        content_parts.extend(["", ""])

    content_parts.extend([
        i18n.get('pdf_question', 'QUESTION'),
        separator,
        question if question else i18n.get('no_question', 'No question'),
        "", "",
        i18n.get('pdf_answer', 'ANSWER'),
        separator,
        response if response else i18n.get('no_response', 'No response'),
        "", "",
    ])

    if include_model_info:
        prefs = get_prefs()
        ai_id = panel.get_selected_ai() or "unknown"
        model_config = prefs.get('models', {}).get(ai_id, {})
        content_parts.extend([
            i18n.get('pdf_model_info', 'AI MODEL INFORMATION'),
            separator,
        ])
        if model_config.get('display_name'):
            content_parts.append(
                f"{i18n.get('model_provider', 'Provider')}: {model_config['display_name']}"
            )
        if model_config.get('model'):
            content_parts.append(
                f"{i18n.get('model_name', 'Model')}: {model_config['model']}"
            )
        if model_config.get('api_base_url'):
            content_parts.append(
                f"{i18n.get('model_api_url', 'API Base URL')}: {model_config['api_base_url']}"
            )
        content_parts.extend(["", ""])

    content_parts.extend([
        i18n.get('pdf_generated_by', 'GENERATED BY'),
        separator,
        f"{i18n.get('pdf_plugin', 'Plugin')}: Ask AI Plugin (calibre Plugin)",
        "GitHub: https://github.com/sheldonrrr/ask_grok",
        f"{i18n.get('pdf_software', 'Software')}: calibre E-book Manager (https://calibre-ebook.com)",
        f"{i18n.get('pdf_generated_time', 'Generated Time')}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ])
    return '\n'.join(content_parts)


def copy_answer(panel):
    text = get_response_text(panel).strip()
    if not text:
        return
    QApplication.clipboard().setText(text)
    show_action_feedback(panel.response_area, panel.i18n.get('copied', 'Copied!'))


def copy_qa(panel):
    dialog = panel.parent_dialog
    question = ""
    if hasattr(dialog, 'input_area') and dialog.input_area:
        question = dialog.input_area.toPlainText().strip()
    response = get_response_text(panel).strip()
    if not question and not response:
        return
    text = format_qa_content(panel, question, response)
    QApplication.clipboard().setText(text)
    show_action_feedback(panel.response_area, panel.i18n.get('copied', 'Copied!'))


def _resolve_export_path(panel, default_filename, dialog_title_key):
    prefs = get_prefs()
    if hasattr(prefs, 'refresh'):
        prefs.refresh()
    if prefs.get('enable_default_export_folder', False) and prefs.get('default_export_folder', ''):
        return os.path.join(prefs['default_export_folder'], default_filename)
    file_path, _ = QFileDialog.getSaveFileName(
        panel,
        panel.i18n.get(dialog_title_key, 'Export to PDF'),
        default_filename,
        "PDF Files (*.pdf)",
    )
    return file_path or None


def _print_content_to_pdf(file_path, content):
    printer = QPrinter()
    printer.setOutputFileName(file_path)
    doc = QTextDocument()
    doc.setPlainText(content)
    doc.print(printer)


def export_current_pdf(panel):
    dialog = panel.parent_dialog
    parallel_ai_count = getattr(dialog, 'parallel_ai_count', 1)
    if parallel_ai_count > 1:
        export_multi_ai_pdf(panel)
        return

    question = dialog.input_area.toPlainText().strip() if dialog.input_area else ""
    response = panel.response_area.toPlainText().strip()
    if not question and not response:
        return

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    ai_name = panel.get_selected_ai() or "Unknown"
    ai_display_name = get_ai_display_name(ai_name)
    book_title = ""
    if getattr(dialog, 'books_info', None):
        book_title = dialog.books_info[0].title
        book_title = "".join(
            c for c in book_title if c.isalnum() or c in (' ', '-', '_')
        ).strip()[:30]
        book_title = f"_{book_title}" if book_title else ""
    default_filename = f"{ai_display_name}_QA{book_title}_{timestamp}.pdf"
    file_path = _resolve_export_path(panel, default_filename, 'export_pdf_dialog_title')
    if not file_path:
        return
    try:
        content = format_qa_content(panel, question, response)
        _print_content_to_pdf(file_path, content)
        show_action_feedback(
            panel.response_area,
            panel.i18n.get('pdf_exported', 'PDF Exported!'),
        )
    except Exception as e:
        logger.error("导出PDF失败: %s", e, exc_info=True)
        QMessageBox.warning(
            panel,
            panel.i18n.get('error', 'Error'),
            panel.i18n.get('export_pdf_error', 'Failed to export PDF: {0}').format(str(e)),
        )


def export_multi_ai_pdf(panel):
    dialog = panel.parent_dialog
    panels = getattr(dialog, 'response_panels', [])
    question = dialog.input_area.toPlainText().strip() if dialog.input_area else ""
    if not any(p.response_area.toPlainText().strip() for p in panels):
        return

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    file_path = _resolve_export_path(panel, f"Multi-AI_QA_{timestamp}.pdf", 'export_pdf_dialog_title')
    if not file_path:
        return

    i18n = panel.i18n
    separator = "────"
    content_parts = []
    if getattr(dialog, 'book_metadata', None):
        book_metadata = dialog.book_metadata
        content_parts.extend([
            i18n.get('pdf_book_metadata', 'BOOK METADATA'),
            separator,
        ])
        for key, label in (
            ('title', 'metadata_title'),
            ('authors', 'metadata_authors'),
            ('publisher', 'metadata_publisher'),
            ('pubdate', 'metadata_pubdate'),
            ('languages', 'metadata_language'),
        ):
            value = book_metadata.get(key)
            if not value:
                continue
            if isinstance(value, list):
                value = ', '.join(value)
            content_parts.append(f"{i18n.get(label, key)}: {value}")
        content_parts.extend(["", ""])

    content_parts.extend([
        i18n.get('pdf_question', 'QUESTION'),
        separator,
        question if question else i18n.get('no_question', 'No question'),
        "", "",
    ])

    prefs = get_prefs()
    models_config = prefs.get('models', {})
    for i, p in enumerate(panels):
        response = p.response_area.toPlainText().strip()
        if not response:
            continue
        ai_id = p.get_selected_ai() or "unknown"
        model_config = models_config.get(ai_id, {})
        ai_display_name = model_config.get('display_name', ai_id)
        content_parts.extend([
            f"{i18n.get('pdf_answer', 'ANSWER')} {i + 1} ({ai_display_name})",
            separator,
            response, "", "",
            f"{i18n.get('pdf_model_info', 'AI MODEL INFORMATION')} {i + 1}",
            separator,
        ])
        for cfg_key, label in (
            ('display_name', 'model_provider'),
            ('model', 'model_name'),
            ('api_base_url', 'model_api_url'),
        ):
            if model_config.get(cfg_key):
                content_parts.append(
                    f"{i18n.get(label, cfg_key)}: {model_config[cfg_key]}"
                )
        content_parts.extend(["", ""])

    content_parts.extend([
        i18n.get('pdf_generated_by', 'GENERATED BY'),
        separator,
        f"{i18n.get('pdf_plugin', 'Plugin')}: Ask AI Plugin (calibre Plugin)",
        f"GitHub: https://github.com/sheldonrrr/ask_grok",
        f"{i18n.get('pdf_software', 'Software')}: calibre E-book Manager (https://calibre-ebook.com)",
        f"{i18n.get('pdf_generated_time', 'Generated Time')}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ])
    try:
        _print_content_to_pdf(file_path, '\n'.join(content_parts))
        show_action_feedback(panel.response_area, i18n.get('pdf_exported', 'PDF Exported!'))
    except Exception as e:
        logger.error("导出多AI PDF失败: %s", e, exc_info=True)
        QMessageBox.warning(
            panel,
            i18n.get('error', 'Error'),
            i18n.get('export_pdf_error', 'Failed to export PDF: {0}').format(str(e)),
        )


def export_history_pdf(panel):
    dialog = panel.parent_dialog
    if not getattr(dialog, 'books_info', None) or not getattr(dialog, 'response_handler', None):
        return
    history_manager = dialog.response_handler.history_manager
    book_ids = [book.id for book in dialog.books_info]
    all_histories = history_manager.get_related_histories(book_ids)
    if not all_histories:
        QMessageBox.information(
            panel,
            panel.i18n.get('info', 'Information'),
            panel.i18n.get('export_history_insufficient', 'Need at least 1 history record to export.'),
        )
        return

    i18n = panel.i18n
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
    book_title = dialog.books_info[0].title if dialog.books_info else "Unknown"
    safe_title = "".join(
        c for c in book_title if c.isalnum() or c in (' ', '-', '_')
    ).strip()[:30]
    file_path = _resolve_export_path(
        panel,
        f"History_{safe_title}_{timestamp}.pdf",
        'export_all_history_dialog_title',
    )
    if not file_path:
        return

    separator = "────"
    content_parts = [
        separator,
        i18n.get('export_all_history_title', 'ALL Q&A HISTORY'),
        separator, "",
    ]
    if getattr(dialog, 'book_metadata', None):
        book_metadata = dialog.book_metadata
        content_parts.extend([separator, i18n.get('pdf_book_metadata', 'BOOK METADATA'), separator])
        for key, label in (
            ('title', 'metadata_title'),
            ('authors', 'metadata_authors'),
            ('publisher', 'metadata_publisher'),
            ('pubdate', 'metadata_pubyear'),
            ('languages', 'metadata_language'),
        ):
            value = book_metadata.get(key)
            if not value:
                continue
            if key == 'pubdate':
                value = str(value).split('T')[0][:7]
            elif isinstance(value, list):
                value = ', '.join(value)
            content_parts.append(f"{i18n.get(label, key)}: {value}")
        content_parts.append("")

    for idx, history in enumerate(all_histories, 1):
        content_parts.extend([
            separator,
            f"{i18n.get('history_record', 'Record')} #{idx} - {history['timestamp']}",
            separator, "",
            f"{i18n.get('question_label', 'Question')}:",
            history.get('question', i18n.get('no_question', 'No question')),
            "",
        ])
        answers = history.get('answers', {})
        if not answers:
            content_parts.append(i18n.get('no_response', 'No response'))
            content_parts.append("")
            continue
        for ai_id, answer_data in answers.items():
            model_info = answer_data.get('model_info', {})
            if model_info and model_info.get('provider_name'):
                ai_display = model_info['provider_name']
            elif ai_id != 'default':
                ai_display = ai_id.capitalize()
            else:
                ai_display = i18n.get('default_ai', 'Default AI')
            content_parts.extend([
                f"{i18n.get('answer_label', 'Answer')} ({ai_display}):",
                "-" * 40,
            ])
            answer_text = answer_data.get('answer', i18n.get('no_response', 'No response'))
            for pattern, repl in (
                (r'#{1,6}\s+', ''),
                (r'\*\*(.+?)\*\*', r'\1'),
                (r'\*(.+?)\*', r'\1'),
                (r'`(.+?)`', r'\1'),
                (r'```[\s\S]*?```', ''),
                (r'\[(.+?)\]\(.+?\)', r'\1'),
            ):
                answer_text = re.sub(pattern, repl, answer_text)
            content_parts.extend([answer_text, ""])

    content_parts.extend([
        "", separator,
        i18n.get('pdf_generated_by', 'GENERATED BY'),
        separator,
        f"{i18n.get('pdf_plugin', 'Plugin')}: Ask AI Plugin (calibre Plugin)",
        f"{i18n.get('pdf_github', 'GitHub')}: https://github.com/sheldonrrr/ask_grok",
        f"{i18n.get('pdf_software', 'Software')}: calibre E-book Manager (https://calibre-ebook.com)",
        f"{i18n.get('pdf_generated_time', 'Generated Time')}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"{i18n.get('total_records', 'Total Records')}: {len(all_histories)}",
        separator,
    ])
    try:
        _print_content_to_pdf(file_path, '\n'.join(content_parts))
        show_action_feedback(panel.response_area, i18n.get('pdf_exported', 'PDF Exported!'))
    except Exception as e:
        logger.error("导出历史PDF失败: %s", e, exc_info=True)
        QMessageBox.warning(
            panel,
            i18n.get('error', 'Error'),
            i18n.get('export_pdf_error', 'Failed to export PDF: {0}').format(str(e)),
        )


def has_exportable_history(panel):
    dialog = panel.parent_dialog
    if not getattr(dialog, 'books_info', None) or not getattr(dialog, 'response_handler', None):
        return False
    book_ids = [book.id for book in dialog.books_info]
    histories = dialog.response_handler.history_manager.get_related_histories(book_ids)
    return len(histories) >= 1


def build_response_context_menu(panel):
    """构建回答区右键菜单。"""
    from PyQt5.QtWidgets import QMenu

    menu = QMenu(panel.response_area)
    i18n = panel.i18n
    is_ai_search = hasattr(panel.parent_dialog, 'books_info') and not panel.parent_dialog.books_info

    copy_answer_action = menu.addAction(i18n.get('copy_response_btn', 'Copy Answer'))
    copy_answer_action.triggered.connect(lambda: copy_answer(panel))

    copy_qa_action = menu.addAction(i18n.get('copy_qa_btn', 'Copy Q&A'))
    copy_qa_action.triggered.connect(lambda: copy_qa(panel))

    if is_ai_search:
        return menu

    menu.addSeparator()
    export_current_action = menu.addAction(
        i18n.get('export_current_btn', 'Export Q&A as PDF')
    )
    export_current_action.triggered.connect(lambda: export_current_pdf(panel))

    export_history_action = menu.addAction(
        i18n.get('export_history_btn', 'Export History as PDF')
    )
    export_history_action.setEnabled(has_exportable_history(panel))
    export_history_action.triggered.connect(lambda: export_history_pdf(panel))
    return menu
